carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar/',views.add, name='add')
]

musicStore/urls.py
from products.views import ProductListView
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProductListView.as_view(), name='index'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('productos/', include('products.urls')),
    path('carrito/', include('carts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name= 'products'

urlpatterns = [
    path('search/', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDatailView.as_view(), name='product')
]

products/models.py
from django.db import models
import uuid
from django.utils.text import slugify
from django.db.models.signals import pre_save
from brands.models import Brand


class Product(models.Model):

    name = models.CharField(max_length=50)
    brand = models.OneToOneField(Brand, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    stock = models.IntegerField()
    slug = models.SlugField(null=False, unique=True, blank=False)
    image = models.ImageField(upload_to='products/', null=False, blank=False)
    created_at = models.DateTimeField(auto_now=True)

    # def save(self, *args, **kwargs):
    #    self.slug = slugify(self.name)
    #    super(Product, self).save(*args, *kwargs)

    def __str__(self):
        return self.name


def set_slug(sender, instance, *args, **kwargs):  # callback
    if instance.name and not instance.slug:
        slug = slugify(instance.name)
        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                f'{instance.name}, { str(uuid.uuid4())[:8] }'
            )
        instance.slug = slug


pre_save.connect(set_slug, sender=Product)

products/views.py
from typing import List
from django.db.models import query
from django.shortcuts import render
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView
from .models import Product
from django.db.models import Q

class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class ProductDatailView(DetailView):
    model = Product
    template_name = 'products/product.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class ProductSearchListView(ListView):
    template_name = 'products/search.html'

    def get_queryset(self):
        filters = Q(name__icontains=self.query()) | Q(category__name__icontains=self.query())
        return Product.objects.filter(filters)
    
    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.query()
        context['count'] = context['product_list'].count()

        return context

products/templates/products/snippets/list.html
{% for product in product_list %}
         
            {% include 'products/snippets/product.html' with product=product %}
        
        {% endfor %}

products/templates/products/snippets/product.html
 <!--Grid column-->
 <div class="col-lg-3 col-md-6 mb-4">

    <!--Card-->
    <div class="card h-100 w-200">

      <!--Card image-->
      <div class="view overlay">
        {% if product.image %} 
        <img src="{{ product.image.url }}" class="card-img-top"
          alt="" width="200" height="250">
        {% endif %}
        <a>
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>
      <!--Card image-->

      <!--Card content-->
      <div class="card-body text-center">
        <!--Category & Title-->
        <a href="" class="grey-text">
          <h5>{{ product.brand }}</h5>
        </a>
        <h5>
          <strong>
            <a href="" class="dark-grey-text">{{ product.name }}</a>
          </strong>
        </h5>

        <h4 class="font-weight-bold blue-text">
          <strong>${{ product.price }}</strong>
        </h4>
        <a href="{% url 'products:product' product.slug %}">
          <button class="btn btn-primary btn-md my-0 p" type="submit">Ver Mas
            <i class="fas fa-shopping-cart ml-1"></i>
          </button>
        </a>
        

      </div>
      <!--Card content-->

    </div>
    <!--Card-->

  </div>
  <!--Grid column-->

products/templates/products/snippets/search.html
<div class="card mt-4 mb-4">
  <div class="card-body">
    <form action="{% url 'products:search' %}">
      <div class="input-group">
        <input id="msg" type="text" class="form-control" value="{{search}}" name="q" placeholder="Buscador">
        <button class="btn btn-primary btn-md my-0 p" type="submit">Buscar
          <i class="fas fa-shopping-cart ml-1"></i>
        </button>
      </div>
    </form>
  </div>
</div>